name: Auto merge to dev
on:
  push:
    branches:
      - dev-server

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Merge and Push
        run: |
          git checkout dev
          git merge --no-ff dev-server
          git push origin dev